import:
    - 'config/base.yaml'
package:
    - 'decoders.seg_detector_loss'
define:
  - name: train_data
    class: ImageDataset
    data_dir:
        - 'DB_Liao/datasets/Eval_corpus'
    data_list:
        - 'DB_Liao/datasets/Eval_corpus/train_list.txt'
    processes:
        - class: AugmentDetectionData
          augmenter_args:
            - {'cls': 'Affine', 'rotate': [-1, 1]}
          only_resize: False
          keep_ratio: False
        - class: RandomCropData
          size: [320, 320]
          max_tries: 10
        - class: MakeICDARData
        - class: MakeSegDetectionData
        - class: MakeBorderMap
        - class: NormalizeImage
        - class: FilterKeys
          superfluous: ['polygons', 'filename', 'shape', 'ignore_tags', 'is_training']

  - name: validate_data
    class: ImageDataset
    data_dir:
        - 'DB_Liao/datasets/Eval_corpus/'
    data_list:
        - 'DB_Liao/datasets/Eval_corpus/test_list.txt'
    processes:
        - class: AugmentDetectionData
          augmenter_args:
              - ['Resize', {'width': 1280, 'height': 736}]
              # - ['Resize', {'width': 2048, 'height': 1152}]
          only_resize: True
          keep_ratio: False
        - class: MakeICDARData
        - class: MakeSegDetectionData
        - class: NormalizeImage
